### ISSUE TITLE
Piston can still push a block into the first space of a bastion field

### ISSUE THREAD

**Issue by GavJenks** [DevotedMC/Bastion#45] opened 2017-09-06 03:55 UTC
Presumably the intended behavior is not being able to push ANY blocks into a bastion field, but currently, if one is placed 2 blocks outside, then a cobble or whatever placed 1 block outside (i.e. the closest you can place it without being blocked), and then you activate the piston, it will push the block successfully into the field. If cycling with a second block, it won't.

**Comment by ProgrammerDan** [comment] 2017-09-06 04:08
Thanks, I'll check into this. It's probably due to rounding errors on the bastion field.

Does this apply to both square and circle bastions? Which have you tested?

**Comment by GavJenks** [comment] 2017-09-06 04:24
Only square on civclassics

**Comment by ProgrammerDan** [comment] 2017-09-06 05:16
Oh, ofc:

https://github.com/DevotedMC/Bastion/blob/master/src/main/java/isaac/bastion/listeners/BastionDamageListener.java#L97

it's adding the list of blocks, but not "moving" them into their future position, only their current position...

**Comment by ProgrammerDan** [comment] 2017-09-12 03:51
confirmed fixed in PR

**Comment by ProgrammerDan** [comment] 2017-09-12 03:54
Fixed in 2.2.3

**Closed as completed by ProgrammerDan** 2017-09-12 03:54 UTC
Labels: bug
